# : Manager [[[

[mgr]
cwd = { fg = "#e4e2e3" }

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#81ace6", bg = "#81ace6" }
marker_cut = { fg = "#d6e4f7", bg = "#d6e4f7" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#bac8db", bg = "#bac8db" }

# Count
count_copied = { fg = "#0f1c2b", bg = "#d6e4f7" }
count_cut = { fg = "#0f1c2b", bg = "#d6e4f7" }
count_selected = { fg = "#29313c", bg = "#bac8db" }

# Border
border_symbol = "│"
border_style  = { fg = "#bfc7d5" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#29313c", bg = "#bfc7d5", bold = true }
inactive = { fg = "#c8c6c7", bg = "#474748" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#29313c", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#bfc7d5", fg = "#29313c", bold = true }
normal_alt  = { bg = "#474748", fg = "#c8c6c7" }

# Select mode
select_main = { bg = "#c3c7cf", fg = "#2c3137", bold = true }
select_alt  = { bg = "#474748", fg = "#c8c6c7" }

# Unset mode
unset_main = { bg = "#bac8db", fg = "#253140", bold = true }
unset_alt  = { bg = "#474748", fg = "#c8c6c7" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#bfc7d5", bg = "#39393a" }
progress_error = { fg = "#ffb4ab", bg = "#39393a" }

# Permissions
permissions_t = { fg = "#6f788a" }
permissions_w = { fg = "#5678a6" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#5690de" }
permissions_s = { fg = "#6d8dc6" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#bfc7d5" }
active = { fg = "#bac8db", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#bfc7d5" }
value = { fg = "#e4e2e3" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#bfc7d5", bg = "#29313c" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#bfc7d5" }
title = {}
hovered = { fg = "#d6e4f7", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#39393a" }
cand = { fg = "#bfc7d5" }
rest = { fg = "#29313c" }
desc = { fg = "#e4e2e3" }
separator = " ▶ "
separator_style = { fg = "#e4e2e3" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e4e2e3" }
run = { fg = "#e4e2e3" }
footer = { fg = "#2c3137", bg = "#c3c7cf" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#bac8db" }
title_warn = { fg = "#bfc7d5" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e4e2e3" },
    { name = "*/", fg = "#bfc7d5" },
]

# : ]]]
